### ISSUE TITLE
Where is the Magento file structure?

### ISSUE THREAD

**Issue by philipdenys** [mowadigital/magento-docker-compose#2]
When I 'ls' the working magento folder, I can't seem to find the Magento file structure.

Shouldn't this be placed somewhere in the 'docker file'?﻿

**Comment by mowadigital** [comment]
Please watch the video: 
https://www.youtube.com/watch?v=rUlWqxwzku4

**Comment by RavingSmurfGB** [comment]
Unsure if this is still needed but the wonderfull mowa shows it in the video, but to explore the file system of a docker container use:
docker exec -it magento bash

the actual files are stored in /var/www/html so in theory this comose wouldnt be out of the question:
```
    magento:
      container_name: magento
      depends_on:
        - db
      image: alexcheng/magento2:latest
      ports:
        - "24013:80"
      restart: always
      environment:
        MAGENTO_DB_HOST: tooy
        MAGENTO_DB_USER: root
        MAGENTO_DB_PASSWORD: root
        MAGENTO_DB_NAME: root
      volumes:
        - /local/docker-data:/var/www/html
```
